name: Docker Build & Push to Microsoft ACR

on:
  workflow_dispatch:
    inputs:
      deployment_type: 
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Microsoft ACR
        id: login-acr
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build, tag, and push image to Microsoft ACR
        env:
          ACR_REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          ACR_REPOSITORY: ${{ secrets.MICROSOFT_ACR_REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.deployment_type }}
        run: |
          docker build -f ./app_folder/Dockerfile -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
          docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
