name: Docker Build & Push to Microsoft ACR

on:
  workflow_dispatch:
    inputs:
      deployment_type: 
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Microsoft ACR
        id: login-acr
        uses: azure/docker-login@v1
        with:
          login-server: lukmal.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: mWVJkXhprY0rbxa2cPywzXvxqnY9RkL1mBKJwxvy/B+ACRAXY33i

      - name: Build, tag, and push image to Microsoft ACR
        env:
          ACR_REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          ACR_REPOSITORY: ${{ secrets.Microsoft_ACR_REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.deployment_type }}
        run: |
          echo "$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG"
          docker build -f ./app_folder/Dockerfile -t lukmal.azurecr.io/diabetesmodel:latest .
          docker push lukmal.azurecr.io/diabetesmodel:latest
